### PR TITLE
Add asdict_simplified

### PR DESCRIPTION
**Pull request by apragsdale**
This reintroduces `asdict_simplified()` using Graham's start at reformatting it. It also tries to address some of the issues from #58 - flexible specification, but "canonical" simplified output.

Would love suggestions here

### CODE REVIEW

**Comment by grahamgower** [comment]
Nice. Thanks for picking this back up @apragsdale, I really like it! Looks like it just needs a couple more tests. And I'm curious, what does it do if you have symmetric migration between say, 3 or 4 demes?

**Comment by apragsdale** [comment]
> Looks like it just needs a couple more tests. And I'm curious, what does it do if you have symmetric migration between say, 3 or 4 demes?

Yes, more tests needed.. I'll work on that.

Current implementation only reduces symmetric migrations to pairwise, but if there are more demes that are all pairwise symmetric at same rate, I could maybe add a loop using `itertools.combinations` to check all possible combinations that start/end times and rates are all equal, for varying sizes.. need to think about it a bit

**Comment by grahamgower** [comment]
Maybe just check nothing crazy happens, and ignore the difficult case for
now?

**Comment by apragsdale** [comment]
This ends up reintroducing `cloning_rate` and `selfing_rate` at the graph-level for inheriting attributes and passing them up and down to/from epochs. Not sure if this is something we want to do...

**Comment by grahamgower** [comment]
> This ends up reintroducing `cloning_rate` and `selfing_rate` at the graph-level for inheriting attributes and passing them up and down to/from epochs. Not sure if this is something we want to do...

I would prefer if the class attributes matched the data model for a fully-qualified graph. And if the goal is to output the smallest file, then maybe copying what the user specified isn't the right thing anyway? In any event, it's not so important that we have the simplification process doing the best possible job for our first release. In my opinion, the epoch start_time/end_time simplification you have in this PR is really valuable, and that should be the current focus.

To digress about inherited attributes though... How about instead using a "greedy" simplification rule? So, first at the Deme level, take the most-frequent attribute value across the epochs as the default. Then do the same thing at the Graph level, taking the most-frequent value across the demes. It's not perfect, but it should be good enough in the most common cases.

**Comment by jeromekelleher** [comment]
> To digress about inherited attributes though... How about instead using a "greedy" simplification rule? So, first at the Deme level, take the most-frequent attribute value across the epochs as the default. Then do the same thing at the Graph level, taking the most-frequent value across the demes. It's not perfect, but it should be good enough in the most common cases.

Probably the thing to do is to use a parsimony algorithm - we think about inherited attributes as state changes on the object model tree, and the simplified thing we output one of the optimal assignments. I've got some Python code lying around for doing Hartigan parsimony, which will do this and I'm sure it'll be easy enough to adapt.

**Comment by grahamgower** [comment]
> I've got some Python code lying around for doing Hartigan parsimony, which will do this and I'm sure it'll be easy enough to adapt.

Great! Sounds like it really should be its own PR then.

**Comment by jeromekelleher** [comment]
> Great! Sounds like it really should be its own PR then.

Agreed - my suggestion would be to pare this back to start-time/end-time simplification and merge. We can follow up separately on inherited attributes.

**Comment by apragsdale** [comment]
> Agreed - my suggestion would be to pare this back to start-time/end-time simplification and merge. We can follow up separately on inherited attributes.

Ok perfect - I'll pare this back, leaving those attributes at the epoch level, and we can handle that separately.

**Comment by apragsdale** [comment]
Additionally, if there are more than two demes that have compatible symmetric migration (say demes A, B, and C all have symmetric migration with the same rates and start and end times), this returns a compact/simplified graph that lists A<->B, A<->C, B<->C, instead of reducing all three into the same symmetric migration specification. I've got something that is close to reducing those symmetric rates, but it's a bit messier requiring , so I'll open it as its own PR once this one is settled, to see if we like it.

**Review by grahamgower — APPROVED** [review]
LGTM!

**Pull request merged**
