### PR TITLE
Add to/from msprime/stdpopsim conversion functions.

### PR DESCRIPTION
**Pull request by grahamgower**
I expect demes->msprime will be one of the shortest export functions we have. I didn't really test this, other than eyballing the demography debugger output below. So, use at your own risk!

```
$ python demes2msprime.py ../examples/gutenkunst_ooa.yml
Model =  hudson(reference_size=1)
===============================
Epoch: 0 -- 21200.0 generations
===============================
     start     end      growth_rate |     0        1        2        3        4        5
   -------- --------       -------- | -------- -------- -------- -------- -------- --------
0 | 7.3e+03  7.3e+03              0 |     0        0        0        0        0        0
1 |1.23e+04 1.23e+04              0 |     0        0        0        0        0        0
2 | 2.1e+03  2.1e+03              0 |     0        0        0        0        0        0
3 |1.23e+04 1.23e+04              0 |     0        0        0        0      3e-05   1.9e-05
4 |2.97e+04   1e+03         0.00016 |     0        0        0      3e-05      0     9.6e-05
5 |5.41e+04    510          0.00022 |     0        0        0     1.9e-05  9.6e-05     0

Events @ generation 21200.0
   - Population parameter change for 2: initial_size -> 2100 growth_rate -> 0
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 4 & dest 2
                     (equivalent to migration from 2 to 4 forwards in time)
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 5 & dest 2
                     (equivalent to migration from 2 to 5 forwards in time)
   - Migration rate change for (2, 3) to 0.00025
   - Migration rate change for (3, 2) to 0.00025
   - Migration rate change for (4, 3) to 0
   - Migration rate change for (3, 4) to 0
   - Migration rate change for (5, 3) to 0
   - Migration rate change for (3, 5) to 0
   - Migration rate change for (5, 4) to 0
   - Migration rate change for (4, 5) to 0
======================================
Epoch: 21200.0 -- 140000.0 generations
======================================
     start     end      growth_rate |     0        1        2        3        4        5
   -------- --------       -------- | -------- -------- -------- -------- -------- --------
0 | 7.3e+03  7.3e+03              0 |     0        0        0        0        0        0
1 |1.23e+04 1.23e+04              0 |     0        0        0        0        0        0
2 | 2.1e+03  2.1e+03              0 |     0        0        0     0.00025     0        0
3 |1.23e+04 1.23e+04              0 |     0        0     0.00025     0        0        0
4 |  1e+03  5.56e-06        0.00016 |     0        0        0        0        0        0
5 |   510   2.27e-09        0.00022 |     0        0        0        0        0        0

Events @ generation 140000.0
   - Population parameter change for 1: initial_size -> 12300 growth_rate -> 0
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 2 & dest 1
                     (equivalent to migration from 1 to 2 forwards in time)
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 3 & dest 1
                     (equivalent to migration from 1 to 3 forwards in time)
   - Migration rate change for (2, 3) to 0
   - Migration rate change for (3, 2) to 0
=======================================
Epoch: 140000.0 -- 220000.0 generations
=======================================
     start     end      growth_rate |     0        1        2        3        4        5
   -------- --------       -------- | -------- -------- -------- -------- -------- --------
0 | 7.3e+03  7.3e+03              0 |     0        0        0        0        0        0
1 |1.23e+04 1.23e+04              0 |     0        0        0        0        0        0
2 | 2.1e+03  2.1e+03              0 |     0        0        0        0        0        0
3 |1.23e+04 1.23e+04              0 |     0        0        0        0        0        0
4 |5.56e-06 1.53e-11        0.00016 |     0        0        0        0        0        0
5 |2.27e-09 5.17e-17        0.00022 |     0        0        0        0        0        0

Events @ generation 220000.0
   - Population parameter change for 0: initial_size -> 7300 growth_rate -> 0
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 1 & dest 0
                     (equivalent to migration from 0 to 1 forwards in time)
==================================
Epoch: 220000.0 -- inf generations
==================================
     start     end      growth_rate |     0        1        2        3        4        5
   -------- --------       -------- | -------- -------- -------- -------- -------- --------
0 | 7.3e+03  7.3e+03              0 |     0        0        0        0        0        0
1 |1.23e+04 1.23e+04              0 |     0        0        0        0        0        0
2 | 2.1e+03  2.1e+03              0 |     0        0        0        0        0        0
3 |1.23e+04 1.23e+04              0 |     0        0        0        0        0        0
4 |1.53e-11     0           0.00016 |     0        0        0        0        0        0
5 |5.17e-17     0           0.00022 |     0        0        0        0        0        0
```

### CODE REVIEW

**Comment by molpopgen** [comment]
Are you dealing with time scale conversion? Like if times are in generations, or years, they need converting into scaled units?

**Comment by grahamgower** [comment]
No, good catch. How about we add a method to the `DemesGraph` class to return a copy in generations?

**Comment by jeromekelleher** [comment]
Very nice, this is really simple which is a great sign we're doing things right!

**Comment by grahamgower** [comment]
I added an `in_generations()` method and updated a couple of things. It bothers me a little that we can't set population sizes to zero for epochs where the demes don't exist. I've set Ne=1e-9 here, which should be a reasonable indicator that the deme isn't doing much in an epoch.

```
$ python export/demes2msprime.py examples/gutenkunst_ooa.yml
Model =  hudson(reference_size=1)
=============================
Epoch: 0 -- 848.0 generations
=============================
     start     end      growth_rate |     0        1        2        3        4        5
   -------- --------       -------- | -------- -------- -------- -------- -------- --------
0 |  1e-09    1e-09               0 |     0        0        0        0        0        0
1 |  1e-09    1e-09               0 |     0        0        0        0        0        0
2 |  1e-09    1e-09               0 |     0        0        0        0        0        0
3 |1.23e+04 1.23e+04              0 |     0        0        0        0     1.2e-06  7.6e-07
4 |2.97e+04   1e+03           0.004 |     0        0        0     1.2e-06     0    3.84e-06
5 |5.41e+04    510           0.0055 |     0        0        0     7.6e-07 3.84e-06     0

Events @ generation 848.0
   - Population parameter change for 2: initial_size -> 2100 growth_rate -> 0
   - Population parameter change for 4: initial_size -> 1e-09 growth_rate -> 0
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 4 & dest 2
                     (equivalent to migration from 2 to 4 forwards in time)
   - Population parameter change for 5: initial_size -> 1e-09 growth_rate -> 0
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 5 & dest 2
                     (equivalent to migration from 2 to 5 forwards in time)
   - Migration rate change for (2, 3) to 1e-05
   - Migration rate change for (3, 2) to 1e-05
   - Migration rate change for (4, 3) to 0
   - Migration rate change for (3, 4) to 0
   - Migration rate change for (5, 3) to 0
   - Migration rate change for (3, 5) to 0
   - Migration rate change for (5, 4) to 0
   - Migration rate change for (4, 5) to 0
==================================
Epoch: 848.0 -- 5600.0 generations
==================================
     start     end      growth_rate |     0        1        2        3        4        5
   -------- --------       -------- | -------- -------- -------- -------- -------- --------
0 |  1e-09    1e-09               0 |     0        0        0        0        0        0
1 |  1e-09    1e-09               0 |     0        0        0        0        0        0
2 | 2.1e+03  2.1e+03              0 |     0        0        0      1e-05      0        0
3 |1.23e+04 1.23e+04              0 |     0        0      1e-05      0        0        0
4 |  1e-09    1e-09               0 |     0        0        0        0        0        0
5 |  1e-09    1e-09               0 |     0        0        0        0        0        0

Events @ generation 5600.0
   - Population parameter change for 1: initial_size -> 12300 growth_rate -> 0
   - Population parameter change for 2: initial_size -> 1e-09 growth_rate -> 0
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 2 & dest 1
                     (equivalent to migration from 1 to 2 forwards in time)
   - Population parameter change for 3: initial_size -> 1e-09 growth_rate -> 0
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 3 & dest 1
                     (equivalent to migration from 1 to 3 forwards in time)
   - Migration rate change for (2, 3) to 0
   - Migration rate change for (3, 2) to 0
===================================
Epoch: 5600.0 -- 8800.0 generations
===================================
     start     end      growth_rate |     0        1        2        3        4        5
   -------- --------       -------- | -------- -------- -------- -------- -------- --------
0 |  1e-09    1e-09               0 |     0        0        0        0        0        0
1 |1.23e+04 1.23e+04              0 |     0        0        0        0        0        0
2 |  1e-09    1e-09               0 |     0        0        0        0        0        0
3 |  1e-09    1e-09               0 |     0        0        0        0        0        0
4 |  1e-09    1e-09               0 |     0        0        0        0        0        0
5 |  1e-09    1e-09               0 |     0        0        0        0        0        0

Events @ generation 8800.0
   - Population parameter change for 0: initial_size -> 7300 growth_rate -> 0
   - Population parameter change for 1: initial_size -> 1e-09 growth_rate -> 0
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 1 & dest 0
                     (equivalent to migration from 0 to 1 forwards in time)
================================
Epoch: 8800.0 -- inf generations
================================
     start     end      growth_rate |     0        1        2        3        4        5
   -------- --------       -------- | -------- -------- -------- -------- -------- --------
0 | 7.3e+03  7.3e+03              0 |     0        0        0        0        0        0
1 |  1e-09    1e-09               0 |     0        0        0        0        0        0
2 |  1e-09    1e-09               0 |     0        0        0        0        0        0
3 |  1e-09    1e-09               0 |     0        0        0        0        0        0
4 |  1e-09    1e-09               0 |     0        0        0        0        0        0
5 |  1e-09    1e-09               0 |     0        0        0        0        0        0
```

**Comment by jeromekelleher** [comment]
> It bothers me a little that we can't set population sizes to zero for epochs where the demes don't exist.

Is this an msprime issue? If so, please do open an issue - now is the time for making changes!

**Comment by grahamgower** [comment]
Looks like flake8 is smoking crack! (but only for python3.6, it's happy with python3.8)
```
./demes/convert/msprime_.py:1:7: E999 SyntaxError: invalid syntax
from typing import List, Mapping, Tuple
      ^
1     E999 SyntaxError: invalid syntax
```

**Comment by grahamgower** [comment]
I think I ended up with something fairly sane here, although mypy screams about the `eq=` attrib parameter not matching attr's type annotations. Not sure how to monkey patch type signatures...

**Pull request merged**
