### PR TITLE
Paper outline

### PR DESCRIPTION
**Pull request by apragsdale**
Thought I'd get a draft/outline of an eventual paper up here. Hope this isn't way too premature! :)

### CODE REVIEW

**Comment by molpopgen** [comment]
Makes sense, and this prevents @apragsdale and I from suggesting we do it in R markdown. 🤣

**Comment by grahamgower** [comment]
Wow! This looks really good, thanks @apragsdale! Do we want to include this here though, or have a separate repository for the manuscript?

**Comment by jeromekelleher** [comment]
Yes, this is *awesome* thanks @apragsdale! But I second the idea of spinning this into its own repo. There's no point in weighing down the software repo here with latex etc, and it'll make it easier to keep track of issues on the paper if we can use the issue tracker for that. Small focused repos are good.

**Comment by apragsdale** [comment]
Ok, will do! That makes perfect sense to me. I'll make a demes paper repo and share.

**Pull request closed without merging**
